### PR TITLE
Bank statement import idempotency

### PR DESCRIPTION
**Pull request by michielbdejong**
Created some unused code and a failing test for this, will try to put it together

### CODE REVIEW

**Comment by michielbdejong** [comment]
Weird:
```
$ PREJOURNAL_ADMIN_PARTY=true DB_DATABASE=testing DB_USER=michiel DB_PASSWORD= DB_HOST=localhost DB_DRIVER=pdo_pgsql ./vendor/bin/phpunit tests/ImportBankStatementTest.php 
PHPUnit 9.5.20 #StandWithUkraine

E                                                                   1 / 1 (100%)
Have 0 movements with these details, adding 1!int(1)
Have 0 movements with these details, adding 1!int(1)
Have 2 need 1array(2) {
  [0]=>
  array(11) {
    ["id"]=>
    int(1)
    ["type_"]=>
    string(7) "payment"
    ["fromcomponent"]=>
    int(1)
    ["tocomponent"]=>
    int(2)
    ["timestamp_"]=>
    string(19) "2022-03-31 12:00:00"
    ["amount"]=>
    string(4) "60.5"
    ["movementid"]=>
    int(1)
    ["userid"]=>
    int(1)
    ["sourcedocumentformat"]=>
    string(11) "asnbank-CSV"
    ["sourcedocumentfilename"]=>
    string(83) "/Volumes/Michiel Docker/gh/pondersource/prejournal/tests/fixtures/asnbank-CSV.csv#0"
    ["description"]=>
    string(66) "outside movement from bank statement: OVB  'Fictional transaction'"
  }
  [1]=>
  array(11) {
    ["id"]=>
    int(2)
    ["type_"]=>
    string(7) "payment"
    ["fromcomponent"]=>
    int(1)
    ["tocomponent"]=>
    int(2)
    ["timestamp_"]=>
    string(19) "2022-03-31 12:00:00"
    ["amount"]=>
    string(4) "60.5"
    ["movementid"]=>
    int(1)
    ["userid"]=>
    int(1)
    ["sourcedocumentformat"]=>
    string(11) "asnbank-CSV"
    ["sourcedocumentfilename"]=>
    string(83) "/Volumes/Michiel Docker/gh/pondersource/prejournal/tests/fixtures/asnbank-CSV.csv#0"
    ["description"]=>
    string(66) "outside movement from bank statement: OVB  'Fictional transaction'"
  }
}
```
But
```sql
testing=# select * from movements;;
 id |  type_  | fromcomponent | tocomponent |     timestamp_      | amount 
----+---------+---------------+-------------+---------------------+--------
  1 | payment |             1 |           2 | 2021-01-01 12:00:00 |   60.5
  2 | payment |             3 |           1 | 2021-01-01 12:00:00 |   60.5
(2 rows)
```

**Comment by michielbdejong** [comment]
Why does it see the wrong from and to components for movement 2?

**Review by ishifoev — APPROVED** [review]
Do you send the same movement twice, or the movement 2 not save in database?

**Comment by michielbdejong** [comment]
> Why does it see the wrong from and to components for movement 2?

That was fixed! It was a bug, it was doing INSERT twice instead of SELECT + INSERT in https://github.com/pondersource/prejournal/pull/105/files#diff-6ef6259f3c04772764c115dd908243df0e82596aac2a837f420c2dffa88b0c50R50

**Pull request merged**
