### PR TITLE
Fix the problem for time-pondersource.com

### PR DESCRIPTION
**Pull request by ishifoev**

### CODE REVIEW

**Comment by michielbdejong** [comment]
@ishifoev can you give some more information about "the problem" and what you changed to fix it here?

**Comment by michielbdejong** [comment]
Maybe you were trying this out on localhost and you hadn't set it to open mode?
As the error message says, `print-timesheet-json` only works in open mode. On heroku, you can see there is a config var `PREJOURNAL_OPEN_MODE` set to `true`.

**Comment by ishifoev** [comment]
@michielbdejong Yes the problem fixed now

**Comment by ishifoev** [comment]
Yes I didn't try it with PREJOURNAL_OPEN_MODE

**Pull request merged**
