### PR TITLE
Working with export for another people can take data

### PR DESCRIPTION
**Pull request by ishifoev**
#90

### CODE REVIEW

**Comment by michielbdejong** [comment]
Awesome!! I will have a look next week

**Comment by michielbdejong** [comment]
```
curl -d'["timesheet"]' https://<user>:<pass>@time.pondersource.com/v1/print-timesheet-json
```

**Review by michielbdejong — DISMISSED** [review]
I changed the 'INNER JOIN' to a 'LEFT JOIN', so that all movements show up, even if they have not been synced yet.

It seems that the command will return an entire database dump of all movements ever, it would be nice to be able to narrow that down a bit: only for a specific user (from component), project (to component), and maybe add date ranges or paging

The output is a var_dump, not actual valid JSON.

Why does a parameter "timesheet" have to be supplied?

```
php src/cli-single.php print-timesheet-json timesheet
array(3) {
  [0]=>
  object(stdClass)#70 (7) {
    ["id"]=>
    int(10565)
    ["name"]=>
    string(20) "Federated timesheets"
    ["type_"]=>
    string(6) "worked"
    ["timestamp_"]=>
    string(19) "2022-04-21 00:00:00"
    ["amount"]=>
    string(2) "60"
    ["description"]=>
    string(36) "Meeting - discuss unique identifiers"
    ["remote_id"]=>
    string(59) "https://timesheet.dev3.evoludata.com/api/trackers/1/items/1"
  }
  [1]=>
  object(stdClass)#71 (7) {
    ["id"]=>
    int(10566)
    ["name"]=>
    string(5) "admin"
    ["type_"]=>
    string(6) "worked"
    ["timestamp_"]=>
    string(19) "2022-12-26 00:00:00"
    ["amount"]=>
    string(2) "40"
    ["description"]=>
    string(0) ""
    ["remote_id"]=>
    NULL
  }
  [2]=>
  object(stdClass)#72 (7) {
    ["id"]=>
    int(10564)
    ["name"]=>
    string(20) "Federated timesheets"
    ["type_"]=>
    string(6) "worked"
    ["timestamp_"]=>
    string(19) "2022-04-21 00:00:00"
    ["amount"]=>
    string(2) "60"
    ["description"]=>
    string(36) "Meeting - discuss unique identifiers"
    ["remote_id"]=>
    NULL
  }
}
```

**Comment by ishifoev** [comment]
@michielbdejong Outside people that use our command for extracting information will use parameter timesheet or prejournal may be? Yes we can do last 10 or 20 data show up for example or do order by date the last new show up. But how we will handle specific user, when we register only admin user show up, We need add on sync table maybe userId that will be work with both. Yes it is in process working I will remove var dump and change it to echo or return. We have a statements table with componentGrants that question up that need to use or not?

**Pull request merged**
